baseURL = "https://abnowack.com/"
languageCode = "en-us"
theme = "contrast"
title = "Aaron Nowack's Blog"

[params]
  math = true
  description = "my blog"
  title = "test"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
